# -*- coding: utf-8 -*-
"""process_metadata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OslrBVhRaIuemXF1iVsAAvJ4jnDaxQ_P
"""

import pandas as pd

path = 'drive/MyDrive/DriveUploader/'

df = pd.read_csv(path + 'train.csv')
df = df.fillna(0)

print(df.shape)
df.tail()

#drop rows with invalid age
df = df[df['Age'] >0]
#drop row with x-ray view PA
df = df[df['AP/PA'] == 'AP']
#drop sex,age,fronta/lateral,ap/pa colums
df = df.drop(['Sex', 'Age', 'Frontal/Lateral', 'AP/PA'], axis=1)
print(df.shape)

df.tail()

# treat uncertainty, -1 indicates uncertainty will treat it as positive class
types = {'No Finding': int,
                'Enlarged Cardiomediastinum': int,
                'Cardiomegaly': int,
                'Lung Opacity': int,
                'Lung Lesion': int,
                'Edema': int,
                'Consolidation': int,
                'Pneumonia': int,
                'Atelectasis': int,
                'Pneumothorax': int,
                'Pleural Effusion': int,
                'Pleural Other': int,
                'Fracture': int,
                'Support Devices': int
               }

df = df.astype(types)
df.dtypes

# uncertainty treated as positive class 50% and negative class as 50%
import random
for col in df.columns:
  if col == 'Path': 
    continue
  df.loc[(df[col]) == -1] = random.randint(0, 1)

df.iloc[:,1:].sum().plot.barh()

df = df.sample(frac=0.2, replace=True, random_state=1)
print(df.shape)
df.head()

df.iloc[:,1:].sum().plot.barh()

df.to_csv('train_processed.csv')

